# Generated by Django 5.0.5 on 2024-06-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='book_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
