# Generated by Django 5.0.5 on 2024-06-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_purchase_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
