# Generated by Django 5.0.5 on 2024-06-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_book_customuser_is_approved_purchase_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(),
        ),
    ]
