# Generated by Django 5.0.5 on 2024-06-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rental',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
