# Generated by Django 5.0.5 on 2024-06-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
