# Generated by Django 5.0.5 on 2024-06-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_customuser_address_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastname',
        ),
    ]
