# Generated by Django 5.0.5 on 2024-06-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
